# Generated by Django 4.2 on 2025-03-31 23:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_orders_status_alter_ordersitems_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersitems',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='ordersitems',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
